---
abstract: 'easy access to CSV files'
author:
  - 'Daniel B. Boorstein <danboo@cpan.org>'
build_requires:
  Test::More: 0
  Text::CSV_XS: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tie-Handle-CSV
provides:
  Tie::Handle::CSV:
    file: lib/Tie/Handle/CSV.pm
    version: 0.13
  Tie::Handle::CSV::Array:
    file: lib/Tie/Handle/CSV/Array.pm
  Tie::Handle::CSV::Hash:
    file: lib/Tie/Handle/CSV/Hash.pm
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/danboo/perl-tie-handle-csv/
version: 0.13
