---
name: Tie-Handle-CSV
version: 0.12
author:
  - 'Daniel B. Boorstein <danboo@cpan.org>'
abstract: easy access to CSV files
license: perl
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/danboo/perl-tie-handle-csv/
build_requires:
  Test::More: 0
  Text::CSV_XS: 0
configure_requires:
  Module::Build: 0.35
provides:
  Tie::Handle::CSV:
    file: lib/Tie/Handle/CSV.pm
    version: 0.12
  Tie::Handle::CSV::Array:
    file: lib/Tie/Handle/CSV/Array.pm
  Tie::Handle::CSV::Hash:
    file: lib/Tie/Handle/CSV/Hash.pm
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
